version: '3.8'

services:
  teams-bot:
    build: .
    image: transcription-bot-image
    container_name: transcription_teams_bot
    restart: unless-stopped
    ports:
      - "50104:50104"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output:/app/output
      - ./.env:/app/.env
    # The image is built from Playwright which requires IPC host for browser stability
    ipc: host
    # Give the container shm_size to prevent Chromium from crashing on long meetings
    shm_size: '2gb'
